version: '3'

services:

#  app:
#    container_name: project_fastapi_app
#    build:
#          context: /timetable
#    restart: no
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#    environment:
#      - PYTHONPATH=/timetable
#    command:
#      - bash -c 'while !</def/tcp/postgres/5432; do sleep 1; done; uvicorn timetable/main:main_app --host 0.0.0.0 port 8000'
#    env_file:
#      - timetable/.env


  db:
    container_name: project_postgres_db
    image: postgres
    environment:
      POSTGRES_DB: fa
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgres/data


  db_test:
    container_name: test_postgres_db
    image: postgres
    environment:
      POSTGRES_DB: dt
      POSTGRES_USER: root1
      POSTGRES_PASSWORD: root1
    ports:
      - "5433:5433"


  adminer:
    container_name: project_adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"


  redis:
    container_name: project_redis_db
    image: redis
    restart: always
    ports:
      - "6379:6379"

